### ISSUE TITLE
 Array to string conversion

### ISSUE THREAD

**Issue by coresh** [astorm/MagentoSessionAreaBug#1]
Affected only: After initial web server starting and initial opening the first request to magento host (after browser refreshing issue not displayed any more)
Notice: Array to string conversion  in app/code/community/Pulsestorm/Sessionareabug/Model/Observer.php on line 6
#0 app/code/community/Pulsestorm/Sessionareabug/Model/Observer.php(6): mageCoreErrorHandler()
#1 app/code/core/Mage/Core/Model/App.php(1338): Pulsestorm_Sessionareabug_Model_Observer->earlySession()
#2 app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod()
#3 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent()
#4 app/code/core/Mage/Core/Controller/Varien/Front.php(128): Mage::dispatchEvent()
#5 app/code/core/Mage/Core/Model/App.php(749): Mage_Core_Controller_Varien_Front->init()
#6 app/code/core/Mage/Core/Model/App.php(1094): Mage_Core_Model_App->_initFrontController()
#7 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->getFrontController()
#8 app/Mage.php(684): Mage_Core_Model_App->run()
#9 pub/index.php(269): Mage::run()
#10 {main}

**Comment by astorm** [comment]
@coresh -- are you using this module for something productive -- it's main point was to **demonstrate** how an [early session instantiation](http://alanstorm.com/magento_sessions_early) creates a session cookie without the `frontend` or `adminhtml` name, which can cause further problems with Magento.

**Comment by astorm** [comment]
Added context for the purpose of this module to the README -- but if you need further assistance and/or a fix for this, please let us know. 

https://github.com/astorm/MagentoSessionAreaBug/commit/d5f802b6f3b24ad45e6554efb5b0aa9e801cf438
